Add ability to choose a PHP image to use
Automattic/vip-cli pull request #1009
Opened 2022-04-20 09:30 UTC by sjinks

## Description

This PR adds an option to choose a PHP image to use; by default, we use `ghcr.io/automattic/vip-container-images/php-fpm:7.4`.

With this option, users can try newer versions of PHP in their development environment.

## Steps to Test

TBD

2022-04-20 14:48 UTC, jesse-greathouse approved these changes
I tested this PR. Here are my findings:

I found that the create sequence worked as expected, and the following start sequence worked as expected.
![Screen Shot 2022-04-20 at 8 38 50 AM](https://user-images.githubusercontent.com/46167019/164256463-83ff30f1-8a28-4ebe-8f3e-46ccebc9dd81.png)

When I checked the environment profile, the .lando.yml had the correct url for the PHP 8 image:

![Screen Shot 2022-04-20 at 8 42 31 AM](https://user-images.githubusercontent.com/46167019/164256986-0424c57d-8df8-4036-962a-56cf78ded099.png)

I verified that docker was running the correct image:
![Screen Shot 2022-04-20 at 8 46 29 AM](https://user-images.githubusercontent.com/46167019/164257835-814de4de-8e2e-4b8a-9950-d4242a87a882.png)

I verified the dev-env test site is working under PHP 8
![Screen Shot 2022-04-20 at 8 47 42 AM](https://user-images.githubusercontent.com/46167019/164258076-bfbd236d-7c32-409b-84d4-396e38c6d6c8.png)

I am happy to approve this PR.

Thank you for the excellent work, @sjinks !

2022-04-20 21:43 UTC, rinatkhaziev requested changes
THANK YOU!

As discussed today we should present the user with a choice of available versions rather than the full image name to make it friendlier. The default choice should be 7.4 (the simpler option) or if a `@ID` notation is provided it should match that value. - but that could be done later.

2022-04-22 12:03 UTC, sjinks commented
@rinatkhaziev please take a look

2022-04-25 19:38 UTC, rinatkhaziev commented on src/bin/vip-dev-env-update.js
> +			php: currentInstanceData.php,
this would be undefined on older instances so needs to `|| default`

2022-04-25 20:23 UTC, rinatkhaziev requested changes, later dismissed
Thanks, left one inline comment to catch the `php` for already existing environments that wouldn't have that key in the `instanceData`.
I opted to do the following: https://github.com/Automattic/vip/commit/95b738114cbc59789d457b5bb13b3ff0449a4bca

2022-04-26 15:23 UTC, jesse-greathouse commented
I tested the latest changes. This is good to go.
![Screen Shot 2022-04-26 at 9 21 22 AM](https://user-images.githubusercontent.com/46167019/165335714-bcf6aca1-6d67-4e62-b23c-f0816f4a209c.png)

2022-04-26 15:36 UTC, merged