Add login info and documentation link to `dev-env info`
Automattic/vip-cli pull request #1021
Opened 2022-05-02 19:24 UTC by chriszarate

## Description

I use `dev-env` infrequently, and I never remember the default login credentials and they are a hassle to track down. Providing this information feels like it would aid a central use case and streamline usage of `dev-env`.

This info is also helpfully printed when running `dev-env start`.

```
> node dist/bin/vip-dev-env-info.js
 NAME              vip-local
 LOCATION          /Users/czarate/.local/share/vip/dev-environment/vip-local
 SERVICES          devtools, nginx, php, database, memcached, wordpress, mu-plugins
 NGINX URLS        http://vip-local.vipdev.lndo.site/
                   https://vip-local.vipdev.lndo.site/
                   http://*.vip-local.vipdev.lndo.site/
                   https://*.vip-local.vipdev.lndo.site/
 DATABASE          127.0.0.1:57724
 STATUS            UP
 LOGIN URL         http://vip-local.vipdev.lndo.site/wp-admin/
 DEFAULT USERNAME  vipgo
 DEFAULT PASSWORD  password
 DOCUMENTATION     https://docs.wpvip.com/technical-references/vip-local-development-environment/tips/
```

I don't want to overload this output, but this feels very readable and useful.

## Steps to Test

1. Check out PR.
1. Run `npm run build`
1. Run `node ./dist/bin/vip-dev-env-info`
1. Verify cookies are delicious.

2022-05-03 06:36 UTC, pschoffer requested changes
Great idea!

Just a one note, when the environment is down and there is no frontend URL the output looks like this:

```
NAME              vip-local                                                                           
 LOCATION          /home/pavel/.local/share/vip/dev-environment/vip-local                              
 SERVICES          devtools, nginx, php, database, memcached, wordpress                                
 STATUS            DOWN                                                                                
 LOGIN URL         undefinedwp-admin/                                                                  
 DEFAULT USERNAME  vipgo                                                                               
 DEFAULT PASSWORD  password                                                                            
 DOCUMENTATION     https://docs.wpvip.com/technical-references/vip-local-development-environment/tips/ 
 ``` 
 
 I would vote for showing login URL and credentials only `if (frontEndUrl)`.

2022-05-03 06:38 UTC, pschoffer commented
Or not show that login URL ever ... and only leave those static fields you added. Both sound good to me.

2022-05-03 13:07 UTC, chriszarate commented
> I would vote for showing login URL and credentials only if (frontEndUrl).

Good catch, thanks! I find it useful so I left the login URL, but defer to you.

2022-05-04 06:50 UTC, pschoffer approved these changes
Perfect!

2022-05-04 08:12 UTC, pschoffer commented
Merging so that it gets included in the release.

2022-05-04 08:12 UTC, merged