[dev-env] validate client code - look for themes subdirectory
Automattic/vip-cli pull request #1070
Opened 2022-08-08 10:23 UTC by pschoffer

## Description

To prevent folks from linking to an incorrect site-code folder we added basic validation that there is `themes` subdirectory at least.

## Steps to Test

```
npm run build && ./dist/bin/vip-dev-env-create.js --slug test --client-code="/tmp"
```

Or type something like that during wizard.

2022-08-10 02:44 UTC, rinatkhaziev commented
I think we should match the validation in production and list all that is missing. 
For example, I pointed to a copy of my repo that only has a themes folder, I mistakenly point to that folder, and VIP-CLI deems this valid. I spin up. the environment only to realize the site is broken. I get annoyed and open a ticket.

2022-08-10 02:45 UTC, rinatkhaziev requested changes
It's ok :)

2022-08-10 09:00 UTC, pschoffer commented
Done I added the same as the prod check does.

2022-08-10 22:14 UTC, rinatkhaziev commented on src/lib/dev-environment/dev-environment-cli.js
> +			const message = `Provided path "${ providedPath }" is missing following files/folders: ${ missingFiles.join( ', ' ) }`;
```suggestion
			const message = `Provided path "${ providedPath }" is missing following files/folders: ${ missingFiles.join( ', ' ) }. Learn more: https://docs.wpvip.com/technical-references/vip-codebase/#1-wordpress`;
```

2022-08-11 16:33 UTC, rinatkhaziev approved these changes

2022-08-12 11:03 UTC, merged