Update/sw get to use param
Automattic/vip-cli pull request #1084
Opened 2022-08-19 09:33 UTC by pschoffer

## Description

* Adds more help description
* uses positional argument to filter component

## Steps to Test

```
npm run build && ./dist/bin/vip-config-software-get.js @4092 nodejs
```

2022-08-19 16:47 UTC, rinatkhaziev commented on src/bin/vip-config-software-get.js
> +		description: 'Read current software settings for wordpress',
```suggestion
		description: 'Read current software settings for WordPress',
```

2022-08-19 16:48 UTC, rinatkhaziev commented on src/bin/vip-config-software-get.js
> +			console.log( chalk.yellow( 'Note:' ), `Software settings for ${ component } are not supported for this environmnet.` );
```suggestion
			console.log( chalk.yellow( 'Note:' ), `Software settings for ${ component } are not supported for this environment.` );
```

2022-08-19 16:49 UTC, rinatkhaziev commented on src/bin/vip-config-software-get.js
> +	let choosenSettings = [];
Typo here and on, should probably read `chosenSettings` not `choosen`

2022-08-19 16:50 UTC, rinatkhaziev requested changes
A few typos here and there. 

Should we also include the `--format` options in examples?

2022-08-22 07:18 UTC, pschoffer commented
I added the `--format` example and fixed a typo. - Thanks @rinatkhaziev !

Also, the formatting logic was changed based on @chriszarate 's suggestion - https://github.com/Automattic/vip/pull/1083

2022-08-22 13:39 UTC, chriszarate commented on src/bin/vip-config-software-get.js
>  		console.log( chalk.yellow( 'Note:' ), 'Software settings are not supported for this environmnet.' );
```suggestion
		console.log( chalk.yellow( 'Note:' ), 'Software settings are not supported for this environment.' );
```

2022-08-22 13:40 UTC, chriszarate commented on src/bin/vip-config-software-get.js
> +		// TODO throw user error
what does this mean?

2022-08-22 13:43 UTC, chriszarate commented on src/bin/vip-config-software-get.js
> +	const preFormated = chosenSettings
```suggestion
	const preFormatted = chosenSettings
```

2022-08-22 13:43 UTC, chriszarate commented on src/bin/vip-config-software-get.js
> +	console.log( formatData( preFormated, opt.format ) );
```suggestion
	console.log( formatData( preFormatted, opt.format ) );
```

2022-08-23 05:44 UTC, pschoffer commented on src/bin/vip-config-software-get.js
> +		// TODO throw user error
Oh right! Thanks for noticing the TODOs. I introduced these UserError that don't print the usual "Contact customer support" error, but show the error to the user, while still using regular error processing.

Now it got merged so I can use it here. I updated the code and removed the TODOs.

2022-08-23 14:34 UTC, chriszarate approved these changes
👍 🎉

2022-08-24 06:57 UTC, merged