Add login subcommand
Automattic/vip-cli pull request #210
Opened 2018-11-16 15:44 UTC by elazzabi

This adds the login subcommand to the `cli`.

It also fixes these types of errors: (https://github.com/Automattic/vip/commit/6c26502a92e0501524283ad4e9b5ed7fcc30a2ab)
```
✕  Unexpected error: Please contact VIP Support with the following error:
  Error: spawn vip-login ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:19)
    at onErrorNT (internal/child_process.js:413:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

### How to test:
1. clone this branch
2. execute `vip logout`
3. execute `npm link`

#### First test:
4. execute `vip aaa`, **you should be redirected** to the `login` flow
5. when prompted with `Ready? (Y, n)`, respond with `n`. You **should quit the command**.

#### Second test:
4. execute `vip aaa`, and complete the `login` workflow
5. when the `login` workflow is done, your `aaa` command **should execute after**. and you should **get an error that the subcommand isn't defined**

fixes #196

2018-11-16 17:01 UTC, nickdaugherty requested changes
Overall looks good - left a few notes.

I'm not sure if it's related to this PR (I hadn't noticed it before at least), but `vip logout` is throwing a tracks-related error for me:

```
$ vip logout

  ✕  Unexpected error: Please contact VIP Support with the following error:
  ReferenceError: trackEvent is not defined
    at Args.command (/Users/nickdaugherty/www/vip/dist/bin/vip.js:26:7)
    at process._tickCallback (internal/process/next_tick.js:43:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```

Oh also, `vip logout` tries to run `vip login` automatically when you're logged out, which is 🤣 ... guess we need an exception for that one 😄 .

```
$ vip logout

  Welcome to
 
... blah blah...

  To get started, we need an access token for your VIP account. We'll open https://dashboard.wpvip.com/me/cli/token in your web browser; follow the instructions there to continue.

 Ready? No
```

2018-11-16 17:01 UTC, nickdaugherty commented on src/bin/vip.js
> +		const loginSpawn = spawn( process.argv[ 0 ], [ 'dist/bin/vip-login.js' ], { stdio: 'inherit' } );
Rather than requiring an `exit` callback, could we maybe use `spawnSync` to block until `login` finished?

2018-11-16 17:01 UTC, nickdaugherty commented on src/bin/vip.js
> +				return spawn( process.argv[ 0 ], process.argv.slice( 1 ), { stdio: 'inherit' } );
When I use `vip login` to login, and complete the flow, I get a redundant message:

```
 Ready? Yes
 Access Token: [hidden]
You are now logged in!
You are already logged in!
```

I think we need to check if the target command was `login`, and if so, skip the second `spawn` here.

2018-11-19 09:56 UTC, elazzabi commented
other than the `trackEvent` error (a missing import, not sure what `eslint` was doing 🤣 ), all those seems to be some edge cases we need to fix:
+ if it's `login` do not execute the second spawn
+ if it's `logout` do not execute the `login`

I'm not sure if we'll find more edge cases in the future...

We can fix those two ^ by skipping things, or we can rethink how we are approaching things (login before running a command, declaring commands only if logged in (https://github.com/Automattic/vip/issues/211)...) and see if we can make it better once and for all

What do you think @nickdaugherty @joshbetz ?

2018-11-19 15:27 UTC, nickdaugherty commented
> We can fix those two ^ by skipping things, or we can rethink how we are approaching things

For now I'd just suggest adding the exceptions for those 2 commands. There probably _are_ other edge cases we haven't found, but until we know what they are, we won't know if changing the approach will have an impact on those.

2018-11-19 20:50 UTC, joshbetz commented
Are we sure `vip login` is necessary? I think it might only seem confusing because our (internal) CLI has a login command. It should be possible to fix the root issue, `Error: spawn vip-login ENOENT`, without adding this subcommand. My main objection is that the CLI should just handle login for you since every command requires you to be logged in. Is there any case when you'd need just the login command?

2018-11-19 21:20 UTC, nickdaugherty commented
I've seen several developers (internally) attempting to use `vip login` (myself included) - I guess b/c they are assuming that's how you log in, or are used to other tools that use that workflow.

Putting myself in the shoes of a new user that's unfamiliar with how the CLI tool works, the first thing I would probably do is `vip -h` to get a lay of the land. If that doesn't list anything about authentication, it might make me a little confused (until I read docs or tried a command).

Definitely agree that having the auto-login is nice (and we still have that), this just exposes the same functionality so it can be run manually if desired.

2018-11-19 21:22 UTC, joshbetz commented
> If that doesn't list anything about authentication, it might make me a little confused (until I read docs or tried a command).

This is another thing that needs to be fixed because right now it doesn't list anything about anything if you're not logged in. I do think we need better help docs.

2018-11-22 09:19 UTC, elazzabi commented
Do you think fixing the help subcommand should be in this PR or another one? Are we ok to add the `login` subcommand?

2018-11-28 18:18 UTC, elazzabi commented
As discussed, we'll skip adding the `login` subcommand. Instead:
1. Help should display all commands even if not logged in
2. If command isn't correct, display a better message (other than spawn error)

Will probably start another PR and close this :)

cc @nickdaugherty @joshbetz @mjangda

2018-12-04 10:06 UTC, elazzabi commented
this is fixed by #214

2018-12-04 10:06 UTC, closed without merging