Fix interactive commands not working correclty
Automattic/vip-cli pull request #478
Opened 2019-10-12 05:35 UTC by dchymko

## Description

This fixes problems running commands that require user input (such as `wp user create --prompt`). 

Note, this does cause regression in not being able to use TTY chars (arrows) inside of the pseudo-shell, as they are written out as control characters.  

## Steps to Test

1. Check out PR.
2. Run `npm run build`
3. Run `/dist/bin/vip-wp.js --yes  @site.env --  user create --prompt`
4. Confirm that entering data at a prompt results in the next prompt (or command completion)

2019-10-16 13:21 UTC, elazzabi requested changes
Yay tested locally and it works for the subshell 🕺 

I proposed a change where we can remove the subshell check so it can work outside the subshell too, what do you think?

2019-10-16 13:21 UTC, elazzabi commented on src/bin/vip-wp.js
> +			if ( isSubShell && commandRunning && 0 === Buffer.compare( data, Buffer.from( '\r' ) ) ) {
```suggestion
			if ( commandRunning && 0 === Buffer.compare( data, Buffer.from( '\r' ) ) ) {
```

2019-10-16 18:42 UTC, dchymko commented on src/bin/vip-wp.js
> +			if ( isSubShell && commandRunning && 0 === Buffer.compare( data, Buffer.from( '\r' ) ) ) {
Good catch. I thought this wasn't impacted outside of the psuedo-shell but forgot that we `subShellRl.write( )` the single commands as well.

2019-10-17 16:07 UTC, dchymko commented
@elazzabi Do you think we should merge this and then refactor readline to be `close()`-ed and recreated each time?

2019-10-17 17:22 UTC, nickdaugherty commented
My 2 cents - if this causes a known regression, it would be better to go straight to the readline fix.

2019-10-17 18:26 UTC, dchymko commented
> My 2 cents - if this causes a known regression, it would be better to go straight to the readline fix.

Whoops, this is no longer the case now that we've reverted the changes to the terminal setting and simply add the newline char instead.  Removed that from the description.

2019-10-20 22:17 UTC, nickdaugherty approved these changes
LGTM (not tested)

2019-10-22 09:34 UTC, elazzabi approved these changes
Looks good!

2019-10-22 09:35 UTC, merged