Support ES version option
Automattic/vip-cli pull request #832
Opened 2021-08-19 14:14 UTC by pschoffer

## Description

Sets the default version of ElasticSearch to 7.5.1 (to match production environment), also introduces `--elastic-search` option to choose a version during the creation of dev-environment.

## Steps to Test

Try to use `--elastic-search` on dev-env creation.

2021-08-19 14:18 UTC, pauarge requested changes
That looks great, but I'm working on the ARM version of that image and this might change a bit. Do you mind holding this PR off?

2021-08-20 01:07 UTC, rinatkhaziev commented on src/bin/vip-dev-env-create.js
> +	.option( 'elastic-search', 'Explicitly choose ElasticSearch version to use' )
```suggestion
	.option( 'elasticsearch', 'Explicitly choose Elasticыearch version to use' )
```

2021-08-20 01:07 UTC, rinatkhaziev commented on src/lib/constants/dev-environment.js
> +	elasticSearchVersion: '7.5.1',
```suggestion
	elasticsearchVersion: '7.5.1',
```

2021-08-20 01:08 UTC, rinatkhaziev commented on src/lib/dev-environment/dev-environment-cli.js
> +	elasticSearch: string,
```suggestion
	elasticsearch: string,
```

2021-08-20 01:08 UTC, rinatkhaziev commented on src/lib/dev-environment/dev-environment-cli.js
> +		elasticSearch: providedOptions.elasticSearch || DEV_ENVIRONMENT_DEFAULTS.elasticSearchVersion,
```suggestion
		elasticsearch: providedOptions.elasticsearch || DEV_ENVIRONMENT_DEFAULTS.elasticsearchVersion,
```

2021-08-20 01:11 UTC, rinatkhaziev commented
There's no capital `S` in Elasticsearch :) I added suggestions (hoping I didn't miss any). 

Also, thoughts about making an alias of `es` for the argument?

2021-08-20 08:37 UTC, pschoffer commented
> There's no capital S in Elasticsearch :) I added suggestions (hoping I didn't miss any).
Oh I do this every time. Thank you!

> Also, thoughts about making an alias of es for the argument?
There is no native support for option aliases in the args parser we use. We could define another option `-es` and kinda make in this function meant the same thing. But that feels unnecessary to me. What do you think? @rinatkhaziev

2021-08-20 15:39 UTC, rinatkhaziev commented
> There is no native support for option aliases in the args parser we use. We could define another option `-es` and kinda make in this function meant the same thing. But that feels unnecessary to me. What do you think? @rinatkhaziev

Ah if there isn't one  then let's not worry about it. I may be confusing with _some other_ CLI that has `.alias()` method...

2021-08-23 13:38 UTC, pschoffer commented
@rinatkhaziev There are aliases to the command not options though - https://www.npmjs.com/package/args

@pauarge, please let me know when the ES image is ready.

2021-08-23 14:24 UTC, pauarge approved these changes, later dismissed
We are not there yet with the custom ES image, so it's OK to merge this now.

2021-08-24 05:33 UTC, pschoffer commented
Only rebased since reviewed so merging anyway :yolo:

2021-08-24 05:33 UTC, merged